% Index for the Prolog Library Collection repository.

:- use_module(library(filesex)).

index(PlcDir):-
  add_index(plc,             PlcDir)),
    add_index(ap,              plc(ap)),
    add_index(datasets,        plc(datasets)),
      add_index(dbpedia,         datasets(dbpedia)),
    add_index(dcg,             plc(dcg)),
      add_index(flp,             dcg(flp)),
      add_index(nlp,             dcg(nlp)),
    add_index(generics,        plc(generics)),
    add_index(graph_theory,    plc(graph_theory)),
      add_index(dgraph,          graph_theory(dgraph)),
      add_index(rdf_graph,       graph_theory(rdf_graph)),
      add_index(ugraph,          graph_theory(ugraph)),
    add_index(ilp,             plc(ilp)),
    add_index(lod,           plc(lod)),
      add_index(owl,             lod(owl )),
      add_index(rdf,             lod(rdf)),
        add_index(rdf_conv,        rdf(conversion)),
        add_index(rdf_file,        rdf(file)),
        add_index(rdf_man,         rdf(management)),
        add_index(rdf_mt,          rdf(rdf_mt)),
        add_index(rdf_reasoning,   rdf(reasoning)),
        add_index(rdf_term,        rdf(term)),
        add_index(rdf_web,         rdf(web)),
      add_index(rdfs,            lod(rdfs)),
      add_index(skos,            lod(skos)),
      add_index(sparql,        lod(sparql)),
      add_index(void,            lod(void)),
    add_index(logic,           plc(logic)),
    add_index(math,            plc(math)),
    add_index(os,              plc(os)),
    add_index(programming,     plc(programming)),
      add_index(pl,              programming(prolog)),
        add_index(pl_web,          pl(web)),
    add_index(ps,              plc(ps)),
      add_index(tms,             ps(tms)),
        add_index(atms,            tms(atms)),
        add_index(doyle,           tms(doyle)),
    add_index(server,          plc(server)),
    add_index(standards,       plc(standards)),
      add_index(datetime,        standards(date_time)),
      add_index(geo,             standards(geography)),
      add_index(gv,              standards(graphviz)),
      add_index(html,            standards(html)),
      add_index(http,            standards(http)),
        add_index(http_headers,    http(headers)),
        add_index(http_parameters, http(parameters)),
      add_index(lang,            standards(language)),
      add_index(latex,           standards(latex)),
      add_index(svg,             standards(svg)),
      add_index(uri,             standards(uri)),
      add_index(xml,             standards(xml)),
        add_index(xsd,             xml(xsd)),
    add_index(web,             plc(web)),
      add_index(crawler,         web(crawler)).


assert_index(Alias, Path):-
  is_absolute_file_name(Path), !,
  make_directory_path(Path),
  add_index(Alias, Path)).
assert_index(Alias, Path):-
  Path =.. [Parent(Child)],
  absolute_file_name(Parent, ParentDir, [file_type(directory)]),
  directory_file_path(ParentDir, Child, ChildDir),
  make_directory_path(ChildDir),
  add_index(Alias, ChildDir)).

